### ISSUE TITLE
The principal node returns Error when it's tried too many times

### ISSUE THREAD

**Issue by elichai** [scrtlabs/enigma-core#140] opened 2019-05-02 13:25 UTC
**Describe the bug**
When I send 100 requests at the same time to the principal node I get an error around 1 in 10 times.

**To Reproduce**
I'll post a code that spams the principal node with requests.

**Expected behavior**
Shouldn't return an error. either should *wait* for the mutex to be unlocked or change the design.

**Backtrace**
```
Err(Error(JsonRpcError(Error { code: InternalError, message: "Unable to get keys: ErrorMessage { msg: \"Unable to lock Epoch Marker Mutex.\" }", data: None }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } }))
```
@fredfortier

**Comment by fredfortier** [comment] 2019-05-02 21:08
Thanks! It would be helpful if you could post your client.

**Comment by AvishaiW** [comment] 2019-07-31 12:08
@fredfortier what is the status on this issue? Did you manage to get the script from elichai?

**Comment by fredfortier** [comment] 2019-08-01 04:06
I think that this a duplicate of another bug that was fixed by changing the mutex `try_lock` to `lock`. AFAIK - this is fixed.

**Closed as completed by fredfortier** 2019-08-01 04:06 UTC
